version: "3.8"

services:
  app:
    build: /app
    container_name: teamavail_app
    ports:
      - "3000:3000"
    networks:
      - app-net
    volumes:
      - output_json:/app/output
    
networks:
  app-net:
    driver: bridge

volumes:
  output_json:
   